services:
  db:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - helios-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - helios-network

  web:
    build: .
    env_file: .env
    command: gunicorn --bind 0.0.0.0:8000 helios.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/static
      - certs:/etc/ssl
    expose:
      - "8000"
    depends_on:
      - db
      - rabbitmq
    networks:
      - helios-network

  celeryworker:
    build: .
    command: /app/celery_start.sh
    env_file: .env
    depends_on:
      - web
      - rabbitmq
    networks:
      - helios-network
    user: helios

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - certs:/etc/ssl
    depends_on:
      - web
    networks:
      - helios-network

volumes:
  postgres_data:
  certs:
  static_volume:

networks:
  helios-network:
    driver: bridge