version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn helios.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  celeryworker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A helios worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq

volumes:
  postgres_data: